[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/keystore',
    'pallets/trust',
    'pallets/signal',
    'pallets/identity',
    'pallets/certificate',
    'runtime/fennel'
]
